"""add total_quantity to map_stats

Revision ID: 36c8788214c1
Revises: b0e1e2f6ed39
Create Date: 2026-06-24 00:21:06.524517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36c8788214c1'
down_revision: Union[str, Sequence[str], None] = 'b0e1e2f6ed39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'map_stats', sa.Column('total_quantity', sa.Integer(), nullable=False, server_default='0')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('map_stats', 'total_quantity')
    # ### end Alembic commands ###
