"""add sale_events table

Revision ID: 5fab0105d3be
Revises: b8d27b9c53ea
Create Date: 2026-06-23 23:11:25.888927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fab0105d3be'
down_revision: Union[str, Sequence[str], None] = 'b8d27b9c53ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sale_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracked_item_id', sa.Integer(), nullable=False),
    sa.Column('ssi', sa.String(), nullable=False),
    sa.Column('seller_name', sa.String(), nullable=True),
    sa.Column('map_name', sa.String(), nullable=True),
    sa.Column('quantity_sold', sa.Integer(), nullable=False),
    sa.Column('sale_attributed_at', sa.DateTime(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('relisted_ssi', sa.String(), nullable=True),
    sa.Column('relisted_quantity', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tracked_item_id'], ['tracked_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tracked_item_id', 'ssi', 'sale_attributed_at', name='uq_sale_event')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sale_events')
    # ### end Alembic commands ###
