"""initial schema

Revision ID: 60d5dbccf554
Revises: 
Create Date: 2026-06-23 20:11:23.154425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60d5dbccf554'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrape_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('items_attempted', sa.Integer(), nullable=False),
    sa.Column('items_succeeded', sa.Integer(), nullable=False),
    sa.Column('location_lookups_performed', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_name', sa.String(), nullable=False),
    sa.Column('shop_name', sa.String(), nullable=False),
    sa.Column('server_name', sa.String(), nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=True),
    sa.Column('map_name', sa.String(), nullable=True),
    sa.Column('x_pos', sa.Integer(), nullable=True),
    sa.Column('y_pos', sa.Integer(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seller_name', 'shop_name', 'server_name', name='uq_shop_location')
    )
    op.create_table('tracked_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('site_item_id', sa.Integer(), nullable=True),
    sa.Column('server_name', sa.String(), nullable=False),
    sa.Column('store_type', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('poll_interval_override', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_name', 'server_name', 'store_type', name='uq_tracked_item')
    )
    op.create_table('daily_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracked_item_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('is_weekend', sa.Boolean(), nullable=False),
    sa.Column('avg_price', sa.Float(), nullable=False),
    sa.Column('median_price', sa.Float(), nullable=False),
    sa.Column('min_price', sa.Integer(), nullable=False),
    sa.Column('max_price', sa.Integer(), nullable=False),
    sa.Column('total_quantity', sa.Integer(), nullable=False),
    sa.Column('listing_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tracked_item_id'], ['tracked_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tracked_item_id', 'date', name='uq_daily_stat')
    )
    op.create_table('hourly_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracked_item_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('avg_price', sa.Float(), nullable=False),
    sa.Column('median_price', sa.Float(), nullable=False),
    sa.Column('min_price', sa.Integer(), nullable=False),
    sa.Column('max_price', sa.Integer(), nullable=False),
    sa.Column('total_quantity', sa.Integer(), nullable=False),
    sa.Column('listing_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tracked_item_id'], ['tracked_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tracked_item_id', 'date', 'hour', name='uq_hourly_stat')
    )
    op.create_table('listings_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracked_item_id', sa.Integer(), nullable=False),
    sa.Column('scrape_run_id', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('ssi', sa.String(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('seller_name', sa.String(), nullable=True),
    sa.Column('shop_name', sa.String(), nullable=True),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('server_name', sa.String(), nullable=True),
    sa.Column('store_type', sa.String(), nullable=True),
    sa.Column('map_id', sa.Integer(), nullable=True),
    sa.Column('map_name', sa.String(), nullable=True),
    sa.Column('x_pos', sa.Integer(), nullable=True),
    sa.Column('y_pos', sa.Integer(), nullable=True),
    sa.Column('location_source', sa.String(), nullable=True),
    sa.Column('page_num', sa.Integer(), nullable=True),
    sa.Column('rank_on_page', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scrape_run_id'], ['scrape_runs.id'], ),
    sa.ForeignKeyConstraint(['tracked_item_id'], ['tracked_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_observations_item_time', 'listings_observations', ['tracked_item_id', 'observed_at'], unique=False)
    op.create_index('ix_observations_map', 'listings_observations', ['map_id'], unique=False)
    op.create_index('ix_observations_ssi', 'listings_observations', ['ssi'], unique=False)
    op.create_table('map_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracked_item_id', sa.Integer(), nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=True),
    sa.Column('map_name', sa.String(), nullable=True),
    sa.Column('period_start', sa.String(), nullable=False),
    sa.Column('period_end', sa.String(), nullable=False),
    sa.Column('avg_price', sa.Float(), nullable=False),
    sa.Column('listing_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tracked_item_id'], ['tracked_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tracked_item_id', 'map_name', 'period_start', 'period_end', name='uq_map_stat')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('map_stats')
    op.drop_index('ix_observations_ssi', table_name='listings_observations')
    op.drop_index('ix_observations_map', table_name='listings_observations')
    op.drop_index('ix_observations_item_time', table_name='listings_observations')
    op.drop_table('listings_observations')
    op.drop_table('hourly_stats')
    op.drop_table('daily_stats')
    op.drop_table('tracked_items')
    op.drop_table('shop_locations')
    op.drop_table('scrape_runs')
    # ### end Alembic commands ###
