"""add map stat stddev and my listing session dismiss flag

Revision ID: 946cab088001
Revises: 36c8788214c1
Create Date: 2026-06-24 17:05:29.539745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '946cab088001'
down_revision: Union[str, Sequence[str], None] = '36c8788214c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'map_stats', sa.Column('stddev_price', sa.Float(), nullable=False, server_default='0')
    )
    op.add_column(
        'my_listing_sessions',
        sa.Column('dismissed', sa.Boolean(), nullable=False, server_default='0'),
    )
    op.add_column('my_listing_sessions', sa.Column('dismissed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('my_listing_sessions', 'dismissed_at')
    op.drop_column('my_listing_sessions', 'dismissed')
    op.drop_column('map_stats', 'stddev_price')
    # ### end Alembic commands ###
