"""add my-sales tracking tables

Revision ID: b0e1e2f6ed39
Revises: 5fab0105d3be
Create Date: 2026-06-23 23:33:53.083142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0e1e2f6ed39'
down_revision: Union[str, Sequence[str], None] = '5fab0105d3be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias_name')
    )
    op.create_table('item_cost_basis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracked_item_id', sa.Integer(), nullable=False),
    sa.Column('cost_per_unit', sa.Float(), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tracked_item_id'], ['tracked_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('my_listing_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracked_item_id', sa.Integer(), nullable=False),
    sa.Column('ssi', sa.String(), nullable=False),
    sa.Column('seller_name', sa.String(), nullable=False),
    sa.Column('shop_name', sa.String(), nullable=True),
    sa.Column('map_name', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('window_end', sa.DateTime(), nullable=False),
    sa.Column('initial_quantity', sa.Integer(), nullable=False),
    sa.Column('last_known_quantity', sa.Integer(), nullable=False),
    sa.Column('total_quantity_sold', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('cost_per_unit', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tracked_item_id'], ['tracked_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tracked_item_id', 'ssi', name='uq_my_listing_session')
    )
    op.create_table('my_sale_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('tracked_item_id', sa.Integer(), nullable=False),
    sa.Column('map_name', sa.String(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('quantity_sold', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['my_listing_sessions.id'], ),
    sa.ForeignKeyConstraint(['tracked_item_id'], ['tracked_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'occurred_at', name='uq_my_sale_event')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('my_sale_events')
    op.drop_table('my_listing_sessions')
    op.drop_table('item_cost_basis')
    op.drop_table('vendor_aliases')
    # ### end Alembic commands ###
