"""add collector_status table

Revision ID: b8d27b9c53ea
Revises: 60d5dbccf554
Create Date: 2026-06-23 21:28:28.146408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8d27b9c53ea'
down_revision: Union[str, Sequence[str], None] = '60d5dbccf554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collector_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('current_item_name', sa.String(), nullable=True),
    sa.Column('next_cycle_at', sa.DateTime(), nullable=True),
    sa.Column('consecutive_rate_limits', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collector_status')
    # ### end Alembic commands ###
